# Generated by Django 5.2.7 on 2025-10-21 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(choices=[('BOISSON', 'Boisson'), ('FRUIT', 'Fruit'), ('LEGUME', 'Légume'), ('EPICERIE', 'Épicerie'), ('VIANDE', 'Viande'), ('POISSON', 'Poisson'), ('PRODUIT_LAITIER', 'Produit laitier'), ('ELECTRONIQUE', 'Électronique'), ('HABILLEMENT', 'Habillement'), ('JOUET', 'Jouet'), ('JEUX_VIDEO', 'Jeux vidéo'), ('AUTRE', 'Autre')], max_length=255)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_fournisseur', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('adresse', models.TextField(max_length=500)),
                ('catalogue_produits', models.TextField(blank=True, max_length=1000, null=True)),
                ('delais_livraison_jours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableStock',
            fields=[
                ('id_responsable', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeApprovisionnement',
            fields=[
                ('id_commande', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison_prevue', models.DateTimeField()),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=50)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stocks.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_product', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('designation', models.TextField(max_length=500)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_en_stock', models.IntegerField()),
                ('seuil_de_reapprovisionnement', models.IntegerField()),
                ('date_de_peremption', models.DateField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stocks.categorie')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stocks.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueVente',
            fields=[
                ('id_historique_vente', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('quantite_vendue', models.IntegerField()),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chiffre_affaires_journalier', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stocks.produit')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueStock',
            fields=[
                ('id_historique', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('quantite_modifiee', models.IntegerField()),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('type_modification', models.CharField(max_length=50)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stocks.produit')),
            ],
        ),
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id_detail', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stocks.commandeapprovisionnement')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stocks.produit')),
            ],
        ),
        migrations.CreateModel(
            name='AlertStock',
            fields=[
                ('id_alert', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=500)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stocks.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_stocks.produit')),
            ],
        ),
    ]
