# Generated by Django 5.2.7 on 2025-10-23 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='catalogue_produits',
        ),
    ]
